# environment
environment: sandbox
vpc: llama

# s3
bucket_name: cfasandbox2

# stack names
s3_bucket_stack_name: sandbox-llama-s3-bucket-cfasandbox2
s3_bucket_policy_stack_name: sandbox-llama-s3-policy-cfasandbox2