template_path: templates/s3_buckets.py
sceptre_user_data:
  cfasandbox1:
    Tags:
      TestKey: TestValue
      environment: "{{ var.environment }}"
      vpc: "{{ var.vpc }}"
    LifecycleConfiguration:
      - Status: Enabled
        Transitions:
          - StorageClass: GLACIER
            TransitionInDays: "7"
    CorsConfiguration:
      - AllowedMethods:
          - GET
        AllowedOrigins:
          - "*"
stack_name: "{{ var.s3_bucket_stack_name }}"