template_path: templates/s3_bucket_policy.py
parameters:
    BucketName: "cfasandbox1"
dependencies:
  # - sandbox/generic/s3/sandbox-wombat-s3-bucket-cfasandbox1
  - sandbox/generic/s3/s3-bucket
sceptre_user_data:
  # Only one BucketPolicy can be defined per bucket.
  # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html
  CloudTrailPolicy:
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Sid: "AWSCloudTrailAclCheck"
          Effect: "Allow"
          Action:
            - "s3:GetBucketAcl"
          Principal:
            Service: "cloudtrail.amazonaws.com"
          Resource:
              - !stack_output_external sandbox-wombat-s3-bucket-cfasandbox1::cfasandbox1BucketArn
        - Sid: "AWSCloudTrailWrite"
          Effect: "Allow"
          Action:
            - "s3:PutObject"
          Principal:
            Service: "cloudtrail.amazonaws.com"
          Condition:
            StringEquals:
              s3:x-amz-acl: "bucket-owner-full-control"
          Resource:
            - "arn:aws:s3:::cfasandbox1/AWSLogs/580501780015/*"
stack_name: "{{ var.s3_bucket_policy_stack_name }}"